In [2]:
import pandas as pd
import numpy as np 
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler, LabelEncoder
import pickle

In [3]:
df = pd.read_csv('Churn_Modelling.csv')

In [4]:
#Preprocess the data 
df = df.drop(["RowNumber","CustomerId", "Surname"], axis=1)
df

,CreditScore,Geography,Gender,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary,Exited
0,619,France,Female,42,2,0.00,1,1,1,101348.88,1
1,608,Spain,Female,41,1,83807.86,1,0,1,112542.58,0
2,502,France,Female,42,8,159660.80,3,1,0,113931.57,1
3,699,France,Female,39,1,0.00,2,0,0,93826.63,0
4,850,Spain,Female,43,2,125510.82,1,1,1,79084.10,0
...,...,...,...,...,...,...,...,...,...,...,...
9995,771,France,Male,39,5,0.00,2,1,0,96270.64,0
9996,516,France,Male,35,10,57369.61,1,1,1,101699.77,0
9997,709,France,Female,36,7,0.00,1,0,1,42085.58,1
9998,772,Germany,Male,42,3,75075.31,2,1,0,92888.52,1
9999,792,France,Female,28,4,130142.79,1,1,0,38190.78,0

In [5]:
#Encode Categorical variable
label_encoder_gender=LabelEncoder()
df['Gender']=label_encoder_gender.fit_transform(df['Gender'])
df

,CreditScore,Geography,Gender,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary,Exited
0,619,France,0,42,2,0.00,1,1,1,101348.88,1
1,608,Spain,0,41,1,83807.86,1,0,1,112542.58,0
2,502,France,0,42,8,159660.80,3,1,0,113931.57,1
3,699,France,0,39,1,0.00,2,0,0,93826.63,0
4,850,Spain,0,43,2,125510.82,1,1,1,79084.10,0
...,...,...,...,...,...,...,...,...,...,...,...
9995,771,France,1,39,5,0.00,2,1,0,96270.64,0
9996,516,France,1,35,10,57369.61,1,1,1,101699.77,0
9997,709,France,0,36,7,0.00,1,0,1,42085.58,1
9998,772,Germany,1,42,3,75075.31,2,1,0,92888.52,1
9999,792,France,0,28,4,130142.79,1,1,0,38190.78,0

In [6]:
#One hot encode Geography column
from sklearn.preprocessing import OneHotEncoder
geography_encoder = OneHotEncoder()
geo_encoded=geography_encoder.fit_transform(df[["Geography"]])

geo_encoded = geo_encoded.toarray()
geo_columns = geography_encoder.get_feature_names_out(['Geography'])

In [7]:
pd.DataFrame(geo_encoded, columns=geo_columns)

      Geography_France  Geography_Germany  Geography_Spain
0                  1.0                0.0              0.0
1                  0.0                0.0              1.0
2                  1.0                0.0              0.0
3                  1.0                0.0              0.0
4                  0.0                0.0              1.0
...                ...                ...              ...
9995               1.0                0.0              0.0
9996               1.0                0.0              0.0
9997               1.0                0.0              0.0
9998               0.0                1.0              0.0
9999               1.0                0.0              0.0

[10000 rows x 3 columns]

In [8]:
#Combine all columns

df = pd.concat([df.drop(['Geography'], axis=1), pd.DataFrame(geo_encoded, columns=geo_columns)], axis=1)
df

,CreditScore,Gender,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary,Exited,Geography_France,Geography_Germany,Geography_Spain
0,619,0,42,2,0.00,1,1,1,101348.88,1,1.0,0.0,0.0
1,608,0,41,1,83807.86,1,0,1,112542.58,0,0.0,0.0,1.0
2,502,0,42,8,159660.80,3,1,0,113931.57,1,1.0,0.0,0.0
3,699,0,39,1,0.00,2,0,0,93826.63,0,1.0,0.0,0.0
4,850,0,43,2,125510.82,1,1,1,79084.10,0,0.0,0.0,1.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...
9995,771,1,39,5,0.00,2,1,0,96270.64,0,1.0,0.0,0.0
9996,516,1,35,10,57369.61,1,1,1,101699.77,0,1.0,0.0,0.0
9997,709,0,36,7,0.00,1,0,1,42085.58,1,1.0,0.0,0.0
9998,772,1,42,3,75075.31,2,1,0,92888.52,1,0.0,1.0,0.0
9999,792,0,28,4,130142.79,1,1,0,38190.78,0,1.0,0.0,0.0

In [9]:
#Save the enoders and scalers in pickle files

with open('label_encoder_gender.pkl', 'wb') as file: 
    pickle.dump(label_encoder_gender, file)

with open('one_hote_encoder_pickle.pkl', 'wb') as file: 
    pickle.dump(geography_encoder, file)

In [15]:
#Divide our dataset into independent and dependent features
X = df.drop('Exited', axis = 1)
Y = df['Exited']

#Split data into training and testing sets 

X_train, X_test, Y_train, Y_test = train_test_split(X, Y, test_size=0.2, random_state=42)

#Scale the features 

scaler = StandardScaler()
X_train= scaler.fit_transform(X_train)
X_test = scaler.transform(X_test)

In [16]:
#Save the scaler in pickle file

with open('scaler.pkl', 'wb') as file: 
    pickle.dump(scaler, file)

In [17]:
df

,CreditScore,Gender,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary,Exited,Geography_France,Geography_Germany,Geography_Spain
0,619,0,42,2,0.00,1,1,1,101348.88,1,1.0,0.0,0.0
1,608,0,41,1,83807.86,1,0,1,112542.58,0,0.0,0.0,1.0
2,502,0,42,8,159660.80,3,1,0,113931.57,1,1.0,0.0,0.0
3,699,0,39,1,0.00,2,0,0,93826.63,0,1.0,0.0,0.0
4,850,0,43,2,125510.82,1,1,1,79084.10,0,0.0,0.0,1.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...
9995,771,1,39,5,0.00,2,1,0,96270.64,0,1.0,0.0,0.0
9996,516,1,35,10,57369.61,1,1,1,101699.77,0,1.0,0.0,0.0
9997,709,0,36,7,0.00,1,0,1,42085.58,1,1.0,0.0,0.0
9998,772,1,42,3,75075.31,2,1,0,92888.52,1,0.0,1.0,0.0
9999,792,0,28,4,130142.79,1,1,0,38190.78,0,1.0,0.0,0.0

ANN Training

In [22]:
import tensorflow as tf
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense
from tensorflow.keras.callbacks import EarlyStopping, TensorBoard

In [18]:
X_train.shape[1]

12

In [23]:
#Build ANN model

model = Sequential([
    Dense(64, activation="relu", input_shape=(X_train.shape[1],)), #HL1 connected to the input layer
    Dense(32, activation="relu"), #HL2
    Dense(1, activation="sigmoid") #Output layer
])

/home/sikander/miniconda3/lib/python3.12/site-packages/keras/src/layers/core/dense.py:87: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(activity_regularizer=activity_regularizer, **kwargs)

In [25]:
model.summary()

Model: "sequential"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ dense (Dense)                   │ (None, 64)             │           832 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_1 (Dense)                 │ (None, 32)             │         2,080 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_2 (Dense)                 │ (None, 1)              │            33 │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 2,945 (11.50 KB)

 Trainable params: 2,945 (11.50 KB)

 Non-trainable params: 0 (0.00 B)

In [26]:
optimizer = tf.keras.optimizers.Adam(learning_rate=0.01)

In [27]:
#Compile the model

model.compile(optimizer=optimizer, loss="binary_crossentropy", metrics=['accuracy'])

In [33]:
#Set up tensorboard
from datetime import datetime
log_dir='logs/fit' + datetime.now().strftime("%Y%m%d-%H%M%S")
tensorflow_callback=TensorBoard(log_dir=log_dir, histogram_freq=1)

In [34]:
#Set up Early stopping
early_stopping_callback=EarlyStopping(monitor="val_loss", patience=5, restore_best_weights=True)

In [35]:
#Train the model
history = model.fit(X_train, Y_train, validation_data=(X_train, Y_train), epochs=100,
                    callbacks=[tensorflow_callback, early_stopping_callback])

Epoch 1/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - accuracy: 0.8183 - loss: 0.4333 - val_accuracy: 0.8468 - val_loss: 0.3658
Epoch 2/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.8570 - loss: 0.3494 - val_accuracy: 0.8649 - val_loss: 0.3349
Epoch 3/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.8545 - loss: 0.3591 - val_accuracy: 0.8635 - val_loss: 0.3323
Epoch 4/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.8598 - loss: 0.3448 - val_accuracy: 0.8641 - val_loss: 0.3299
Epoch 5/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.8618 - loss: 0.3468 - val_accuracy: 0.8652 - val_loss: 0.3332
Epoch 6/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.8615 - loss: 0.3451 - val_accuracy: 0.8673 - val_loss: 0.3259
Epoch 7/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.8577 - loss: 0.3451 - val_accuracy: 0.8661 - val_loss: 0.3219
Epoch 8/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.8639 - loss: 0.3270 - val_accuracy: 0.8689 - val_loss: 0.3218
Epoch 9/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.8580 - loss: 0.3407 - val_accuracy: 0.8679 - val_loss: 0.3170
Epoch 10/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.8656 - loss: 0.3242 - val_accuracy: 0.8727 - val_loss: 0.3126
Epoch 11/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.8642 - loss: 0.3282 - val_accuracy: 0.8710 - val_loss: 0.3114
Epoch 12/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.8666 - loss: 0.3231 - val_accuracy: 0.8689 - val_loss: 0.3123
Epoch 13/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.8704 - loss: 0.3174 - val_accuracy: 0.8730 - val_loss: 0.3147
Epoch 14/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.8625 - loss: 0.3312 - val_accuracy: 0.8735 - val_loss: 0.3105
Epoch 15/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.8695 - loss: 0.3207 - val_accuracy: 0.8737 - val_loss: 0.3076
Epoch 16/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.8755 - loss: 0.3094 - val_accuracy: 0.8741 - val_loss: 0.3033
Epoch 17/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.8710 - loss: 0.3127 - val_accuracy: 0.8779 - val_loss: 0.3000
Epoch 18/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.8733 - loss: 0.2991 - val_accuracy: 0.8786 - val_loss: 0.2956
Epoch 19/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.8720 - loss: 0.3104 - val_accuracy: 0.8752 - val_loss: 0.3052
Epoch 20/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.8760 - loss: 0.3047 - val_accuracy: 0.8788 - val_loss: 0.2973
Epoch 21/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.8794 - loss: 0.2974 - val_accuracy: 0.8813 - val_loss: 0.2961
Epoch 22/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.8730 - loss: 0.3010 - val_accuracy: 0.8796 - val_loss: 0.2959
Epoch 23/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.8726 - loss: 0.3031 - val_accuracy: 0.8806 - val_loss: 0.2818
Epoch 24/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.8763 - loss: 0.2941 - val_accuracy: 0.8800 - val_loss: 0.2906
Epoch 25/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.8656 - loss: 0.3073 - val_accuracy: 0.8798 - val_loss: 0.2818
Epoch 26/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.8811 - loss: 0.2894 - val_accuracy: 0.8827 - val_loss: 0.2812
Epoch 27/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.8718 - loss: 0.2998 - val_accuracy: 0.8817 - val_loss: 0.2770
Epoch 28/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.8805 - loss: 0.2954 - val_accuracy: 0.8816 - val_loss: 0.2766
Epoch 29/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.8737 - loss: 0.2960 - val_accuracy: 0.8781 - val_loss: 0.2802
Epoch 30/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.8820 - loss: 0.2779 - val_accuracy: 0.8836 - val_loss: 0.2737
Epoch 31/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.8814 - loss: 0.2839 - val_accuracy: 0.8871 - val_loss: 0.2670
Epoch 32/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.8807 - loss: 0.2818 - val_accuracy: 0.8857 - val_loss: 0.2687
Epoch 33/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.8804 - loss: 0.2761 - val_accuracy: 0.8852 - val_loss: 0.2675
Epoch 34/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.8837 - loss: 0.2760 - val_accuracy: 0.8876 - val_loss: 0.2662
Epoch 35/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.8800 - loss: 0.2774 - val_accuracy: 0.8889 - val_loss: 0.2582
Epoch 36/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.8852 - loss: 0.2662 - val_accuracy: 0.8928 - val_loss: 0.2565
Epoch 37/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.8889 - loss: 0.2607 - val_accuracy: 0.8921 - val_loss: 0.2570
Epoch 38/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.8889 - loss: 0.2573 - val_accuracy: 0.8909 - val_loss: 0.2603
Epoch 39/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.8837 - loss: 0.2731 - val_accuracy: 0.8954 - val_loss: 0.2480
Epoch 40/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.8956 - loss: 0.2543 - val_accuracy: 0.8936 - val_loss: 0.2500
Epoch 41/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.8927 - loss: 0.2566 - val_accuracy: 0.8928 - val_loss: 0.2484
Epoch 42/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.8882 - loss: 0.2558 - val_accuracy: 0.8911 - val_loss: 0.2479
Epoch 43/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.8897 - loss: 0.2586 - val_accuracy: 0.8889 - val_loss: 0.2599
Epoch 44/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.8896 - loss: 0.2573 - val_accuracy: 0.8951 - val_loss: 0.2431
Epoch 45/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.8923 - loss: 0.2524 - val_accuracy: 0.8959 - val_loss: 0.2419
Epoch 46/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.8948 - loss: 0.2434 - val_accuracy: 0.8940 - val_loss: 0.2441
Epoch 47/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.8937 - loss: 0.2432 - val_accuracy: 0.8970 - val_loss: 0.2342
Epoch 48/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.8898 - loss: 0.2525 - val_accuracy: 0.8986 - val_loss: 0.2340
Epoch 49/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.8867 - loss: 0.2414 - val_accuracy: 0.8951 - val_loss: 0.2385
Epoch 50/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.8921 - loss: 0.2437 - val_accuracy: 0.8959 - val_loss: 0.2373
Epoch 51/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.8978 - loss: 0.2360 - val_accuracy: 0.8960 - val_loss: 0.2341
Epoch 52/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.8884 - loss: 0.2513 - val_accuracy: 0.8971 - val_loss: 0.2351
Epoch 53/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.8980 - loss: 0.2397 - val_accuracy: 0.9011 - val_loss: 0.2278
Epoch 54/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.8926 - loss: 0.2424 - val_accuracy: 0.8966 - val_loss: 0.2337
Epoch 55/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.8956 - loss: 0.2418 - val_accuracy: 0.8966 - val_loss: 0.2317
Epoch 56/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.8946 - loss: 0.2335 - val_accuracy: 0.8972 - val_loss: 0.2284
Epoch 57/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.9005 - loss: 0.2264 - val_accuracy: 0.9006 - val_loss: 0.2230
Epoch 58/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.8974 - loss: 0.2308 - val_accuracy: 0.9014 - val_loss: 0.2207
Epoch 59/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.8949 - loss: 0.2348 - val_accuracy: 0.9004 - val_loss: 0.2191
Epoch 60/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.8964 - loss: 0.2360 - val_accuracy: 0.8996 - val_loss: 0.2274
Epoch 61/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.8963 - loss: 0.2360 - val_accuracy: 0.9029 - val_loss: 0.2164
Epoch 62/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.8957 - loss: 0.2323 - val_accuracy: 0.8996 - val_loss: 0.2216
Epoch 63/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.8967 - loss: 0.2263 - val_accuracy: 0.9020 - val_loss: 0.2254
Epoch 64/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.8955 - loss: 0.2363 - val_accuracy: 0.8976 - val_loss: 0.2266
Epoch 65/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.8994 - loss: 0.2362 - val_accuracy: 0.9006 - val_loss: 0.2168
Epoch 66/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.8990 - loss: 0.2282 - val_accuracy: 0.9038 - val_loss: 0.2149
Epoch 67/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.9019 - loss: 0.2144 - val_accuracy: 0.9014 - val_loss: 0.2156
Epoch 68/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.9008 - loss: 0.2139 - val_accuracy: 0.9039 - val_loss: 0.2061
Epoch 69/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.9002 - loss: 0.2114 - val_accuracy: 0.9026 - val_loss: 0.2122
Epoch 70/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.9012 - loss: 0.2186 - val_accuracy: 0.9064 - val_loss: 0.2110
Epoch 71/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.8996 - loss: 0.2224 - val_accuracy: 0.8999 - val_loss: 0.2241
Epoch 72/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.8967 - loss: 0.2340 - val_accuracy: 0.9007 - val_loss: 0.2202
Epoch 73/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.9040 - loss: 0.2160 - val_accuracy: 0.9082 - val_loss: 0.1982
Epoch 74/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.8979 - loss: 0.2196 - val_accuracy: 0.9075 - val_loss: 0.2028
Epoch 75/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.9028 - loss: 0.2098 - val_accuracy: 0.9055 - val_loss: 0.2100
Epoch 76/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.9042 - loss: 0.2156 - val_accuracy: 0.9049 - val_loss: 0.2101
Epoch 77/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.8972 - loss: 0.2237 - val_accuracy: 0.9049 - val_loss: 0.2076
Epoch 78/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.9027 - loss: 0.2149 - val_accuracy: 0.9057 - val_loss: 0.2071

In [36]:
model.save('model.h5')

WARNING:absl:You are saving your model as an HDF5 file via `model.save()` or `keras.saving.save_model(model)`. This file format is considered legacy. We recommend using instead the native Keras format, e.g. `model.save('my_model.keras')` or `keras.saving.save_model(model, 'my_model.keras')`.

In [1]:
#Launch tensorboard extension

%load_ext tensorboard

In [2]:
%tensorboard --logdir logs/fit*